CREATE PROCEDURE `ActivateSuspensionTimes`(
	IN ids NVARCHAR(256)
)
BEGIN

	DROP TEMPORARY TABLE IF EXISTS IDS;
	CREATE TEMPORARY TABLE IDS( TXT TEXT );
	INSERT INTO IDS VALUES(ids);

	DROP TEMPORARY TABLE IF EXISTS IDS_TEMP;
	CREATE TEMPORARY TABLE IDS_TEMP(VAL INT);
	SET @insertToTempSql = CONCAT("INSERT INTO IDS_TEMP (VAL) VALUES ('", REPLACE(( SELECT GROUP_CONCAT(DISTINCT TXT) AS DATA FROM IDS), ",", "'),('"),"');");
	PREPARE STMT1 FROM @insertToTempSql;
	EXECUTE STMT1;

	DROP TEMPORARY TABLE IF EXISTS IDS;

	UPDATE ServicePackageSuspensionTimes t1
	SET t1.IsActive = FALSE
	WHERE EXISTS (SELECT VAL FROM IDS_TEMP WHERE VAL = t1.Id);
END