
CREATE PROCEDURE `GetExpiredOutContract`()
BEGIN
	SELECT `oc`.`Id`,
    `oc`.`Culture`,
    `oc`.`CreatedDate`,
    `oc`.`UpdatedDate`,
    `oc`.`CreatedBy`,
    `oc`.`UpdatedBy`,
    `oc`.`IsActive`,
    `oc`.`DisplayOrder`,
    `oc`.`IdentityGuid`,
    `oc`.`ContractCode`,
    `oc`.`AgentCode`,
    `oc`.`MarketAreaId`,
    `oc`.`MarketAreaName`,
    `oc`.`ProjectId`,
    `oc`.`ProjectName`,
    `oc`.`ContractTypeId`,
    `oc`.`ContractStatusId`,
    `oc`.`ContractorId`,
    `oc`.`SignedUserId`,
    `oc`.`SalesmanId`,
    `oc`.`Description`,
    `oc`.`FiberNodeInfo`,
    `oc`.`ContractNote`,
    `oc`.`AgentContractCode`,
    `oc`.`OrganizationUnitId`,
    `oc`.`CashierUserId`,
    `oc`.`Payment_Form` AS `Form`,
    `oc`.`Payment_Method` AS `Method`,
    `oc`.`Payment_Address` AS `Address`,
    `oc`.`TimeLine_RenewPeriod` AS `RenewPeriod`,
    `oc`.`TimeLine_PaymentPeriod` AS `PaymentPeriod`,
    `oc`.`TimeLine_Expiration` AS `Expiration`,
    `oc`.`TimeLine_Liquidation` AS `Liquidation`,
    `oc`.`TimeLine_Effective` AS `Effective`,
    `oc`.`TimeLine_Signed` AS `Signed`,
	`t4`.`Id`,
	`t4`.`IdentityGuid`,
	`t4`.`ContractorCode`,
	`t4`.`ContractorFullName`,
	`t4`.`ContractorPhone`,
	`t4`.`ContractorEmail`,
	`t4`.`ContractorFax`,
	`t4`.`ContractorAddress`,
	`t4`.`ContractorIdNo`,
	`t4`.`ContractorTaxIdNo`,
	`t4`.`IsEnterprise`,
	`t4`.`IsBuyer`
	FROM OutContracts oc
    INNER JOIN Contractors t4 ON t4.Id = oc.ContractorId
    WHERE oc.IsDeleted = FALSE
		AND DATE_SUB(oc.TimeLine_Expiration, INTERVAL 1 MONTH) < CURDATE();
END