CREATE PROCEDURE `GetNeedToPaymentContractServices`()
BEGIN
	IF NOT EXISTS (SELECT 1 FROM TemporaryPayingContracts)
	THEN
	BEGIN
			INSERT INTO TemporaryPayingContracts(`OutContractId`, `ServicePackageId`)
			SELECT oc.Id, t5.Id
			FROM OutContracts oc
			INNER JOIN OutContractServicePackages t5 ON t5.OutContractId = oc.Id AND t5.IsDeleted = FALSE
			WHERE  oc.IsDeleted = FALSE
				AND oc.ContractStatusId NOT IN (1, 4, 5)
				AND t5.StatusId = 0
				AND t5.TimeLine_NextBilling IS NOT NULL
				AND t5.TimeLine_NextBilling <= DATE_ADD(CURDATE(), INTERVAL 1 MONTH);
				
		END;
	END IF;
	
	SELECT `oc`.`Id`,
	`oc`.`CurrencyUnitId`,
	`oc`.`CurrencyUnitCode`,
	`oc`.`Culture`,
	`oc`.`CreatedDate`,
	`oc`.`UpdatedDate`,
	`oc`.`CreatedBy`,
	`oc`.`UpdatedBy`,
	`oc`.`IsActive`,
	`oc`.`DisplayOrder`,
	`oc`.`IdentityGuid`,
	`oc`.`ContractCode`,
	`oc`.`AgentCode`,
	`oc`.`MarketAreaId`,
	`oc`.`MarketAreaName`,
	`oc`.`ProjectId`,
	`oc`.`ProjectName`,
	`oc`.`ContractTypeId`,
	`oc`.`ContractStatusId`,
	`oc`.`ContractorId`,
	`oc`.`SignedUserId`,
	`oc`.`SalesmanId`,
	`oc`.`Description`,    
	`oc`.`TotalTaxPercent`,
	`oc`.`TotalTaxAmount`,
	`oc`.`InstallationFee`,
	`oc`.`OtherFee`,
	`oc`.`SubTotal`,
	`oc`.`GrandTotalBeforeTax`,
	`oc`.`GrandTotal`,
	`oc`.`FiberNodeInfo`,
	`oc`.`ContractNote`,
	`oc`.`AgentContractCode`,
	`oc`.`OrganizationUnitId`,
	`oc`.`CashierUserId`,
	`oc`.`CashierUserName`,
	`oc`.`CashierFullName`,
	`oc`.`EquipmentAmount`,
	`oc`.`ServicePackageAmount`,
	`oc`.`NumberBillingLimitDays`,
	`oc`.`Payment_Form` AS `Form`,
	`oc`.`Payment_Method` AS `Method`,
	`oc`.`Payment_Address` AS `Address`,    
	`oc`.`TimeLine_Signed` AS `Signed`,
	`oc`.`TimeLine_Effective` AS `Effective`,
	`oc`.`TimeLine_Liquidation` AS `Liquidation`,
	`oc`.`TimeLine_Expiration` AS `Expiration`,
	`oc`.`TimeLine_PaymentPeriod` AS `PaymentPeriod`,
	`oc`.`TimeLine_RenewPeriod` AS `RenewPeriod`,
	`t4`.`Id`,
	`t4`.`IdentityGuid`,
	`t4`.`ContractorCode`,
	`t4`.`ContractorFullName`,
	`t4`.`ContractorPhone`,
	`t4`.`ContractorEmail`,
	`t4`.`ContractorFax`,
	`t4`.`ContractorAddress`,
	`t4`.`ContractorIdNo`,
	`t4`.`ContractorTaxIdNo`,
	`t4`.`IsEnterprise`,
	`t4`.`IsBuyer`,
	`t5`.`Id`,
	`t5`.`IsActive`,
	`t5`.`ServicePackageId`,
	`t5`.`ServiceId`,
	`t5`.`ServiceName`,
	`t5`.`PackageName`,
	`t5`.`IsFreeStaticIp`,
	`t5`.`InternationalBandwidth`,
	`t5`.`DomesticBandwidth`,
	`t5`.`CustomerCode`,
	`t5`.`TaxAmount`,
	`t5`.`TaxPercent`,
	`t5`.`PackagePrice`,
	`t5`.`SubTotalBeforeTax`,
	`t5`.`SubTotal`,
	`t5`.`GrandTotal`,
	`t5`.`GrandTotalBeforeTax`,
	`t5`.`EquipmentAmount`,
	`t5`.`InstallationFee`,
	`t5`.`CId`,
	`t5`.`OutletChannelId`,
	`t5`.`DomesticBandwidthUom`,
	`t5`.`InternationalBandwidthUom`,
	`t5`.`OtherFee`,
	`t5`.`CurrencyUnitId`,
	`t5`.`CurrencyUnitCode`,
	`t5`.`TimeLine_PaymentPeriod` AS `PaymentPeriod`,
	`t5`.`TimeLine_Effective` AS `Effective`,
	`t5`.`TimeLine_Signed` AS `Signed`,
	`t5`.`TimeLine_LatestBilling` AS `LatestBilling`,
	`t5`.`TimeLine_NextBilling` AS `NextBilling`,
	`t5`.`TimeLine_PrepayPeriod` AS `PrepayPeriod`,	
	`t6`.`OutContractServicePackageId` AS `OutContractServicePackageId`,
	`t6`.`TaxCategoryId` AS `TaxCategoryId`,
	`t6`.`TaxCategoryName` AS `TaxCategoryName`,
	`t6`.`TaxValue` AS `TaxValue`,	
	cep.Id AS `Id`,
	cep.CurrencyUnitId AS `CurrencyUnitId`,
	cep.CurrencyUnitCode AS `CurrencyUnitCode`,
	cep.PointType AS `PointType`,
	cep.InstallationFee AS `InstallationFee`,
	cep.OtherFee AS `OtherFee`,
	cep.MonthlyCost AS `MonthlyCost`,
	cep.EquipmentAmount AS `EquipmentAmount`,
	'' AS `EndPointInstallationSpliter`,
	cep.`InstallationAddress_Building` AS `Building`,
	cep.`InstallationAddress_Floor` AS `Floor`,
	cep.`InstallationAddress_RoomNumber` AS `RoomNumber`,
	cep.`InstallationAddress_Street` AS `Street`,
	cep.`InstallationAddress_District` AS `District`,
	cep.`InstallationAddress_DistrictId` AS `DistrictId`,
	cep.`InstallationAddress_City` AS `City`,
	cep.`InstallationAddress_CityId` AS `CityId`,

	csp.Id AS `Id`,
	csp.CurrencyUnitId AS `CurrencyUnitId`,
	csp.CurrencyUnitCode AS `CurrencyUnitCode`,
	csp.PointType AS `PointType`,
	csp.InstallationFee AS `InstallationFee`,
	csp.OtherFee AS `OtherFee`,
	csp.MonthlyCost AS `MonthlyCost`,
	csp.EquipmentAmount AS `EquipmentAmount`,
	'' AS `StartPointInstallationSpliter`,
	csp.`InstallationAddress_Building` AS `Building`,
	csp.`InstallationAddress_Floor` AS `Floor`,
	csp.`InstallationAddress_RoomNumber` AS `RoomNumber`,
	csp.`InstallationAddress_Street` AS `Street`,
	csp.`InstallationAddress_District` AS `District`,
	csp.`InstallationAddress_DistrictId` AS `DistrictId`,
	csp.`InstallationAddress_City` AS `City`,
	csp.`InstallationAddress_CityId` AS `CityId`
	FROM TemporaryPayingContracts voc
	INNER JOIN OutContracts oc ON voc.OutContractId = oc.Id
	INNER JOIN Contractors t4 ON t4.Id = oc.ContractorId
	INNER JOIN OutContractServicePackages t5 ON t5.Id = voc.ServicePackageId
	INNER JOIN OutputChannelPoints cep ON cep.Id = t5.EndPointChannelId
	LEFT JOIN OutputChannelPoints csp ON csp.Id = t5.StartPointChannelId
	LEFT JOIN OutContractServicePackageTaxes t6 ON t5.Id = t6.OutContractServicePackageId;
END